MAG-354: Allow success order placement on oney pending payment
payplug/payplug-magento2 pull request #218
Opened 2024-07-24 13:51 UTC by TristanBouchierAgenceDnD

changelog: fixed

# ⚠️ Requirements
Reviewer, please take a look at those requirements before merging on `master` :

- [X] Check that plugin version has been upgaded and are identical in both `composer.json` and `Helper/Config.php` files

2024-08-01 18:55 UTC, AntoineKociubaAgenceDnD requested changes

2024-08-01 18:55 UTC, AntoineKociubaAgenceDnD commented on Controller/Payment/PaymentReturn.php
> +     * @return bool
to remove, useless

2024-08-01 18:55 UTC, AntoineKociubaAgenceDnD commented on Controller/Payment/PaymentReturn.php
> +     * @param Payment|null $payment
to remove, useless

2024-08-01 18:55 UTC, AntoineKociubaAgenceDnD commented on Controller/Payment/PaymentReturn.php
> +                return (str_contains($paymentMethod['type'], 'oney') && $paymentMethod['is_pending'] === true);
Which PHP version should we remain compatible with ? ⚠️

2024-08-01 18:55 UTC, AntoineKociubaAgenceDnD commented on Controller/Payment/PaymentReturn.php
> +    public function execute(): mixed
`mixed` is not a proper type. Type properly and more specifically instead, keeping in mind PHP compatibility constraints also

2024-08-01 18:55 UTC, AntoineKociubaAgenceDnD commented on Controller/Payment/PaymentReturn.php
>       * @return mixed
to remove, useless

2024-08-05 08:26 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/PaymentReturn.php
>       * @return mixed
OK

2024-08-05 08:27 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/PaymentReturn.php
> +                return (str_contains($paymentMethod['type'], 'oney') && $paymentMethod['is_pending'] === true);
For now 8.0+, Antoine will see with Dani, but all the developments have been made so far in this direction

2024-08-05 08:27 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/PaymentReturn.php
> +     * @param Payment|null $payment
OK

2024-08-05 08:27 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/PaymentReturn.php
> +     * @return bool
OK

2024-08-05 08:31 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/PaymentReturn.php
> +    public function execute(): mixed
OK

2024-08-05 09:05 UTC, TristanBouchierAgenceDnD reviewed
Changes were made

2024-08-05 17:46 UTC, AntoineKociubaAgenceDnD approved these changes

2024-08-07 13:29 UTC, merged