MAG-316: Fix phtmls escapers and add strict types for php 8
payplug/payplug-magento2 pull request #220
Opened 2024-07-31 14:40 UTC by TristanBouchierAgenceDnD

changelog: fixed

# ⚠️ Requirements
Reviewer, please take a look at those requirements before merging on `master` :

- [X] Check that plugin version has been upgraded and are identical in both `composer.json` and `Helper/Config.php` files

2024-08-01 18:49 UTC, AntoineKociubaAgenceDnD requested changes

2024-08-01 18:49 UTC, AntoineKociubaAgenceDnD commented on view/frontend/templates/oney/simulation_wrapper_checkout.phtml
>      <?= $block->getChildBlock('payplug-payments-product-oney-simulation')->toHtml(); ?>
@TristanBouchierAgenceDnD `getChildHtml` directly

2024-08-01 18:49 UTC, AntoineKociubaAgenceDnD commented on view/frontend/templates/oney/simulation_content.phtml
> +                <a href="<?= $escaper->escapeHtmlAttr($block->getMoreInfoUrlWithoutFees()); ?>" target="_blank" download>
@TristanBouchierAgenceDnD `escapeUrl` for links/URLs. To verify on all current PR files as well.

BTW, what is the oldest version of Magento to remain compatible with ? 
Because `$escaper` was introduced since 2.4, and should break on oldest versions I guess ⚠️

2024-08-01 18:49 UTC, AntoineKociubaAgenceDnD commented on view/frontend/templates/info/ondemand.phtml
> +                            <?= /* @noEscape */ nl2br($escaper->escapeHtml($formattedValue)) ?>
`/* @noEscape */` to remove, as content is escaped

2024-08-01 18:49 UTC, AntoineKociubaAgenceDnD commented on view/frontend/templates/info/installment_plan.phtml
> +                            <?= /* @noEscape */ nl2br($escaper->escapeHtml($formattedValue)) ?>
`/* @noEscape */` to remove, as content is escaped

2024-08-01 18:49 UTC, AntoineKociubaAgenceDnD commented on view/frontend/templates/info/default.phtml
> +                            <?= /* @noEscape */ nl2br($escaper->escapeHtml($formattedValue)) ?>
`/* @noEscape */` to remove, as content is escaped

2024-08-01 18:49 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/info/default.phtml
> +                    <?= /* @noEscape */ nl2br($escaper->escapeHtml($formattedValue)) ?>
`/* @noEscape */` to remove, as content is escaped

2024-08-01 18:49 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/info/default.phtml
>                      $formattedValue = implode("\n", $block->getValueAsArray($value, true));
`PHP_EOL` constant instead of `"\n"`

2024-08-01 18:49 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +                      title="<?= $escaper->escapeHtml(__('Description')) ?>"
`escapeHtmlAttr`

2024-08-01 18:49 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +            <button title="<?= $escaper->escapeHtml($buttonTitle); ?>"
`escapeHtmlAttr`

2024-08-01 18:49 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +                    <option value="<?= $escaper->escapeHtml($languageCode) ?>"
`escapeHtmlAttr`

2024-08-01 18:49 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +                   title="<?= $escaper->escapeHtml(__('Mobile / Email')) ?>" class="admin__control-text required-entry"
`escapeHtmlAttr`

2024-08-01 18:49 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +                    <option value="<?= $escaper->escapeHtml($typeCode) ?>"
`escapeHtmlAttr`

2024-08-02 07:11 UTC, antoine-fontaine commented on view/adminhtml/templates/form/ondemand.phtml
>  <fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */ $code ?>"
If MAG-316 main subject is to fix escaper, could you please change these `noEscape` ?

2024-08-02 07:11 UTC, antoine-fontaine commented on view/adminhtml/templates/form/ondemand.phtml
>                        maxlength="<?= \Payplug\Payments\Helper\Ondemand::DESCRIPTION_MAX_LENGTH ?>"
If you have time for this, you can simplify FQN by using an alias : 
`use Payplug\Payments\Helper\Ondemand as OndemandHelper;`
And use it here

2024-08-02 12:36 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
>  <fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */ $code ?>"
@antoine-fontaine it is a tricky one, as it is already escaped at teh beginning of the template.

@TristanBouchierAgenceDnD let's be clear, simple, and consistent -> Add escape on display(s) directly, and keep the top file only for variables declaration/creation. It will be less confusing in the future this way

2024-08-05 09:31 UTC, TristanBouchierAgenceDnD commented on view/frontend/templates/oney/simulation_wrapper_checkout.phtml
>      <?= $block->getChildBlock('payplug-payments-product-oney-simulation')->toHtml(); ?>
OK

2024-08-05 09:35 UTC, TristanBouchierAgenceDnD commented on view/frontend/templates/oney/simulation_content.phtml
> +                <a href="<?= $escaper->escapeHtmlAttr($block->getMoreInfoUrlWithoutFees()); ?>" target="_blank" download>
Antoine will see with Dani for the version, but for now as Hyva is 2.4 we makes the changes for a 2.4+ and php 8.0+

2024-08-05 09:46 UTC, TristanBouchierAgenceDnD commented on view/frontend/templates/oney/simulation_content.phtml
> +                <a href="<?= $escaper->escapeHtmlAttr($block->getMoreInfoUrlWithoutFees()); ?>" target="_blank" download>
OK

2024-08-05 09:47 UTC, TristanBouchierAgenceDnD commented on view/frontend/templates/info/ondemand.phtml
> +                            <?= /* @noEscape */ nl2br($escaper->escapeHtml($formattedValue)) ?>
OK

2024-08-05 09:47 UTC, TristanBouchierAgenceDnD commented on view/frontend/templates/info/installment_plan.phtml
> +                            <?= /* @noEscape */ nl2br($escaper->escapeHtml($formattedValue)) ?>
OK

2024-08-05 09:47 UTC, TristanBouchierAgenceDnD commented on view/frontend/templates/info/default.phtml
> +                            <?= /* @noEscape */ nl2br($escaper->escapeHtml($formattedValue)) ?>
OK

2024-08-05 09:47 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/info/default.phtml
> +                    <?= /* @noEscape */ nl2br($escaper->escapeHtml($formattedValue)) ?>
OK

2024-08-05 09:59 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/info/default.phtml
>                      $formattedValue = implode("\n", $block->getValueAsArray($value, true));
OK

2024-08-05 10:00 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +                      title="<?= $escaper->escapeHtml(__('Description')) ?>"
OK

2024-08-05 10:01 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +                    <option value="<?= $escaper->escapeHtml($languageCode) ?>"
OK

2024-08-05 11:02 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +                   title="<?= $escaper->escapeHtml(__('Mobile / Email')) ?>" class="admin__control-text required-entry"
OK

2024-08-05 11:02 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +                    <option value="<?= $escaper->escapeHtml($typeCode) ?>"
OK

2024-08-05 11:05 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
>  <fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */ $code ?>"
OK

2024-08-05 11:06 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
>                        maxlength="<?= \Payplug\Payments\Helper\Ondemand::DESCRIPTION_MAX_LENGTH ?>"
OK

2024-08-05 17:51 UTC, AntoineKociubaAgenceDnD requested changes

2024-08-05 17:51 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $escaper->escapeHtml($code) ?>"
`escapeHtmlAttr` ici

2024-08-05 17:51 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +        <label class="admin__field-label" for="<?= $escaper->escapeHtml($code) ?>_sent_by">
`escapeHtmlAttr` ici

2024-08-05 17:51 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +            <select id="<?= $escaper->escapeHtml($code) ?>_sent_by" name="payment[sent_by]"
`escapeHtmlAttr` ici

2024-08-05 17:51 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +        <label class="admin__field-label" for="<?= $escaper->escapeHtml($code) ?>_sent_by_value">
`escapeHtmlAttr` ici

2024-08-05 17:51 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +            <input type="text" id="<?= $escaper->escapeHtml($code) ?>_sent_by_value" name="payment[sent_by_value]"
`escapeHtmlAttr` ici

2024-08-05 17:51 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +        <label class="admin__field-label" for="<?= $escaper->escapeHtml($code) ?>_language">
`escapeHtmlAttr` ici

2024-08-05 17:51 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +            <select id="<?= $escaper->escapeHtml($code) ?>_language"
`escapeHtmlAttr` ici

2024-08-05 17:51 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +        <label class="admin__field-label" for="<?= $escaper->escapeHtml($code) ?>_description">
`escapeHtmlAttr` ici

2024-08-05 17:51 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +            <textarea id="<?= $escaper->escapeHtml($code) ?>_description"
`escapeHtmlAttr` ici

2024-08-05 17:51 UTC, AntoineKociubaAgenceDnD commented on view/frontend/templates/customer/cardList.phtml
> +                    <a href="<?= $escaper->escapeHtmlAttr($block->getDeleteCardUrl($customerCardId)) ?>">
`escapeUrl` ici

2024-08-22 11:28 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $escaper->escapeHtml($code) ?>"
OK

2024-08-22 11:28 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +        <label class="admin__field-label" for="<?= $escaper->escapeHtml($code) ?>_sent_by">
OK

2024-08-22 11:29 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +            <select id="<?= $escaper->escapeHtml($code) ?>_sent_by" name="payment[sent_by]"
OK

2024-08-22 11:29 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +        <label class="admin__field-label" for="<?= $escaper->escapeHtml($code) ?>_sent_by_value">
OK

2024-08-22 11:29 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +            <input type="text" id="<?= $escaper->escapeHtml($code) ?>_sent_by_value" name="payment[sent_by_value]"
OK

2024-08-22 11:29 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +        <label class="admin__field-label" for="<?= $escaper->escapeHtml($code) ?>_language">
OK

2024-08-22 11:29 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +            <select id="<?= $escaper->escapeHtml($code) ?>_language"
OK

2024-08-22 11:30 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +        <label class="admin__field-label" for="<?= $escaper->escapeHtml($code) ?>_description">
OK

2024-08-22 11:30 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/form/ondemand.phtml
> +            <textarea id="<?= $escaper->escapeHtml($code) ?>_description"
OK

2024-08-22 11:32 UTC, TristanBouchierAgenceDnD commented on view/frontend/templates/customer/cardList.phtml
> +                    <a href="<?= $escaper->escapeHtmlAttr($block->getDeleteCardUrl($customerCardId)) ?>">
I can't because escapeUrl doesn't work with the url parameters, and the function getDeleteCardUrl return 
return $this->_urlBuilder->getUrl('payplug_payments/customer/cardDelete', [
            'customer_card_id' => $customerCardId
        ]);

2024-08-22 14:40 UTC, TristanBouchierAgenceDnD commented on view/frontend/templates/customer/cardList.phtml
> +                    <a href="<?= $escaper->escapeHtmlAttr($block->getDeleteCardUrl($customerCardId)) ?>">
As seen here https://agencednd.slack.com/archives/C073M9NPYS1/p1724337484210059?thread_ts=1724327663.785269&cid=C073M9NPYS1 escapeUrl seem to work for this case, so it's updated

2024-08-22 14:41 UTC, AntoineKociubaAgenceDnD commented on view/frontend/templates/customer/cardList.phtml
> +                    <a href="<?= $escaper->escapeHtmlAttr($block->getDeleteCardUrl($customerCardId)) ?>">
`escapeUrl` should properly work with URL parameter in the magento way (/key1/param1/key2/param2), cf the provided exemple above.

Example from the core : 

- `Template` : https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Multishipping/view/frontend/templates/checkout/overview.phtml#L87
- `Block (URL generation with params)` : https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Multishipping/Block/Checkout/Overview.php#L334

2024-08-22 16:21 UTC, AntoineKociubaAgenceDnD requested changes

2024-08-22 16:21 UTC, AntoineKociubaAgenceDnD commented on view/frontend/templates/checkout/formjs.phtml
> +    <script src="<?= $escaper->escapeHtmlAttr($url); ?>"></script>
`escapeUrl` here

2024-08-23 06:49 UTC, TristanBouchierAgenceDnD commented on view/frontend/templates/checkout/formjs.phtml
> +    <script src="<?= $escaper->escapeHtmlAttr($url); ?>"></script>
OK

2024-08-23 08:17 UTC, AntoineKociubaAgenceDnD approved these changes

2024-09-11 08:23 UTC, merged