MAG-310 into develop
payplug/payplug-magento2 pull request #229
Opened 2024-08-28 13:22 UTC by TristanBouchierAgenceDnD

# ⚠️ Requirements
Reviewer, please take a look at those requirements before merging on `master` :

- [X] Check that plugin version has been upgrated and are identical in both `composer.json` and `Helper/Config.php` files

Ticket : https://payplug-prod.atlassian.net/browse/MAG-310

2024-09-23 18:00 UTC, AntoineKociubaAgenceDnD requested changes

2024-09-23 18:00 UTC, AntoineKociubaAgenceDnD commented on view/frontend/templates/info/default.phtml
> +                            <?= $escaper->escapeHtml(nl2br($escaper->escapeHtml($formattedValue))); ?>
@TristanBouchierAgenceDnD from core examples, the first top escaper added here should not be added, otherwise, it will probably break `<br>` just previously added by the `nl2br` function call : https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Payment/view/frontend/templates/info/default.phtml#L24

To revert here

2024-09-23 18:00 UTC, AntoineKociubaAgenceDnD commented on view/frontend/templates/info/default.phtml
> +    <dt class="title"><?= $escaper->escapeHtml($title); ?></dt>
@TristanBouchierAgenceDnD no need to escape again here, as already escaped above, when variable is defined.

To revert here

2024-09-23 18:00 UTC, AntoineKociubaAgenceDnD commented on view/frontend/templates/info/default.phtml
> +                <caption class="table-caption"><?= $escaper->escapeHtml($title); ?></caption>
@TristanBouchierAgenceDnD no need to escape again here, as already escaped above, when variable is defined.

To revert here

2024-09-23 18:00 UTC, AntoineKociubaAgenceDnD commented on view/adminhtml/templates/info/default.phtml
> +                    <?= $escaper->escapeHtml(nl2br($escaper->escapeHtml($formattedValue))); ?>
@TristanBouchierAgenceDnD same here (see [view/frontend/templates/info/default.phtml](https://github.com/payplug/payplug-magento2/pull/229/files#diff-b5b02cc76bf7c59d750f391c1898be52d2f97fd85f9dc76b1786b71bf6c73b64R28))

2024-09-23 18:00 UTC, AntoineKociubaAgenceDnD commented on Block/OneyInfo.php
> +    protected function buildPaymentDetails(Payment $payment, Order $order): array
@TristanBouchierAgenceDnD type `$order` param with interface instead of concrete class

2024-09-23 18:00 UTC, AntoineKociubaAgenceDnD commented on Block/OndemandInfo.php
> +     *  Get some admin specific information in format of array($label => $value)
@TristanBouchierAgenceDnD revert extra space added

2024-09-23 18:00 UTC, AntoineKociubaAgenceDnD commented on Block/Info.php
> +    protected function buildPaymentDetails(Payment $payment, Order $order): array
@TristanBouchierAgenceDnD type `$order` param with interface instead of concrete class

2024-09-25 08:08 UTC, TristanBouchierAgenceDnD commented on view/frontend/templates/info/default.phtml
> +                            <?= $escaper->escapeHtml(nl2br($escaper->escapeHtml($formattedValue))); ?>
OK

2024-09-25 08:13 UTC, TristanBouchierAgenceDnD commented on view/adminhtml/templates/info/default.phtml
> +                    <?= $escaper->escapeHtml(nl2br($escaper->escapeHtml($formattedValue))); ?>
OK

2024-09-25 08:14 UTC, TristanBouchierAgenceDnD commented on view/frontend/templates/info/default.phtml
> +                <caption class="table-caption"><?= $escaper->escapeHtml($title); ?></caption>
OK

2024-09-25 08:14 UTC, TristanBouchierAgenceDnD commented on view/frontend/templates/info/default.phtml
> +    <dt class="title"><?= $escaper->escapeHtml($title); ?></dt>
OK

2024-09-25 08:17 UTC, TristanBouchierAgenceDnD commented on Block/OneyInfo.php
> +    protected function buildPaymentDetails(Payment $payment, Order $order): array
OK

2024-09-26 15:28 UTC, AntoineKociubaAgenceDnD requested changes

2024-09-30 11:17 UTC, TristanBouchierAgenceDnD commented on Block/OneyInfo.php
> +     * @param Order $order
OK

2024-09-30 11:41 UTC, AntoineKociubaAgenceDnD approved these changes

2024-09-30 11:42 UTC, merged