Release/v4.2.0 to Master
payplug/payplug-magento2 pull request #238
Opened 2024-10-30 16:48 UTC by TristanBouchierAgenceDnD

# ⚠️ Requirements
Reviewer, please take a look at those requirements before merging on `master` :

- [X] Check that plugin version has been upgrated and are identical in both `composer.json` and `Helper/Config.php` files

2024-11-06 08:17 UTC, Dnd-Mafer requested changes

2024-11-06 08:17 UTC, Dnd-Mafer commented on Controller/Payment/PaymentReturn.php
> +        return false;
`if` is useless and you can simply all using null-safe operator
```php
 return $order?->getPayment()?->getMethod() === StandardConfig::METHOD_CODE && $this->config->isStandardPaymentModeDeferred();
```

2024-11-06 08:17 UTC, Dnd-Mafer commented on Cron/AutoCaptureDeferredPayments.php
> +        $quoteIds = [];
useless, you can simply use `array_keys` on `$quotePaymentsToOrderPayments`

2024-11-06 08:17 UTC, Dnd-Mafer commented on Cron/AutoCaptureDeferredPayments.php
> +            $deferredPaymentValidationDate = new DateTime();
Shouldn't you create this var out of the loop ?

2024-11-06 08:17 UTC, Dnd-Mafer commented on Cron/AutoCaptureDeferredPayments.php
> +            if ($difference->days >= 6) {
use constant (or even best a configuration) instead of hardcoded 6

2024-11-06 08:17 UTC, Dnd-Mafer commented on Helper/Data.php
> +        return false;
```php
return (bool)$payment?->getAdditionalInformation('is_authorized');
```

2024-11-06 08:17 UTC, Dnd-Mafer commented on Observer/SetDeferredAfterInvoiceOrderStatus.php
> +            || !$order->getPayment()?->getAdditionalInformation('was_deferred')
use a var for `$order->getPayment()`

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD requested changes

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +            )->setIsCustomerNotified(true)->save();
Repository should be used for the save operation, instead of direct action on entity (let's check if this extra save is really needed, or if defining comment status history before the transaction above can do it in one go)

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +            )->setIsCustomerNotified(false)->save();
Remove the save, as it is already done below

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +        private Message $laminas,
`$laminas` is not really representative and clear enough. Why not `$message` instead, to keep it simple and consistent ?

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +        $this->laminas->setSubject($subject);
as this is called in a loop context, I guess relying on factory and fresh object on each iteration could be better.

Check also `Magento\Framework\Mail\EmailMessageInterface`, `Magento\Framework\Mail\TransportInterface` and usage on `Magento\Newsletter\Model\Queue\TransportBuilder` for example

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Config.php
> +        $defaultEmail = $this->getConfigValue('email', ScopeConfigInterface::SCOPE_TYPE_DEFAULT, '0');
Rely on existing core constant instead of 0

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Config.php
> +    public function setPayplugApiKey(mixed $storeId, bool $isSandbox): void
mixed should not be used

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Config.php
> +    public function getApiKey($isSandbox, mixed $storeId = null): ?string
mixed should not be used

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Config.php
>          if ($isSandbox) {
condition should be simplified in one line

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Config.php
>          $environmentMode = $this->getConfigValue('environmentmode', ScopeInterface::SCOPE_STORE, $store);
can be simplified in one line ($environmentMode variable only used once, no value to declare it)

=== instead ? (be careful to cast if needed)

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Config.php
> +    public function isOneClick(mixed $storeId = null): mixed
mixed should not be used

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Config.php
>          return $this->getConfigValue('payment_page') == self::PAYMENT_PAGE_INTEGRATED;
=== instead ? (be careful to cast if needed)

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Config.php
>          return $this->getConfigValue('payment_page') == self::PAYMENT_PAGE_EMBEDDED;
=== instead ? (be careful to cast if needed)

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Config.php
> +    public function setConfigValue(string $field, string $value, string $scope = ScopeInterface::SCOPE_STORE, mixed $scopeId = null, ?string $path = null): void
mixed should not be used

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Transaction/ApplePayBuilder.php
>  use Magento\Quote\Model\Quote;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Transaction/BancontactBuilder.php
>  use Magento\Quote\Model\Quote;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Transaction/IdealBuilder.php
>  use Magento\Quote\Model\Quote;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Transaction/InstallmentPlanBuilder.php
>  use Magento\Quote\Model\Quote;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Transaction/MybankBuilder.php
>  use Magento\Quote\Model\Quote;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Transaction/OndemandBuilder.php
>  use Magento\Quote\Model\Quote;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Transaction/OneyBuilder.php
>  use Magento\Quote\Model\Quote;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Transaction/OneyBuilder.php
>  use Magento\Sales\Model\Order\Item;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Transaction/SatispayBuilder.php
>  use Magento\Quote\Model\Quote;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Transaction/StandardBuilder.php
>  use Magento\Quote\Model\Quote;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Helper/Transaction/StandardBuilder.php
> +        //Manage the deferred paiement mode
space missing after //

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Observer/SetDeferredAfterInvoiceOrderStatus.php
> +use Magento\Sales\Model\Order;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Observer/SetDeferredAfterInvoiceOrderStatus.php
> +use Magento\Sales\Model\OrderRepository;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Observer/SetDeferredProcessingOrderStatus.php
> +use Magento\Sales\Model\Order;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Observer/SetDeferredProcessingOrderStatus.php
> +<?php
No particular comments/headers  in general ? (other files to be checked also if needed)

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Plugin/CaptureStandardDeferredPayment.php
> +use Magento\Quote\Model\QuoteRepository;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Plugin/CaptureStandardDeferredPayment.php
> +use Magento\Sales\Model\Order;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Plugin/CaptureStandardDeferredPayment.php
> +use Magento\Sales\Model\OrderRepository;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Plugin/CreatePayplugTransactionOnAuthorizeOnly.php
> +use Magento\Quote\Model\QuoteRepository;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Setup/Patch/Data/CreateFailedCaptureOrderStatus.php
> +use Magento\Sales\Model\Order;
Rely on interface instead

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Setup/Patch/Data/CreateFailedCaptureOrderStatus.php
> +        $this->moduleDataSetup->startSetup();
No need to disable foreign key check here, to remove

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on Setup/Patch/Data/CreateFailedCaptureOrderStatus.php
> +        $this->moduleDataSetup->endSetup();
No need to disable foreign key check here, to remove

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on etc/crontab.xml
> +            <schedule>0 * * * *</schedule>
Could be nice to make it configurable from back office instead, so final customers would have the possibility to adjust it depending on their needs and context

2024-11-06 10:31 UTC, AntoineKociubaAgenceDnD commented on etc/crontab.xml
> +    <group id="default">
Might be better to consider a dedicated group

2024-11-06 12:50 UTC, TristanBouchierAgenceDnD commented on Api/Data/OrderInterface.php
> +     * Status the happens when a payment capture fail, before invoice creation, associated to the pending_payment state
OK

2024-11-06 12:51 UTC, TristanBouchierAgenceDnD commented on Helper/Data.php
> +        return false;
OK

2024-11-06 12:53 UTC, TristanBouchierAgenceDnD commented on Observer/SetDeferredAfterInvoiceOrderStatus.php
> +            || !$order->getPayment()?->getAdditionalInformation('was_deferred')
OK

2024-11-06 12:55 UTC, TristanBouchierAgenceDnD commented on Plugin/CaptureStandardDeferredPayment.php
> +        $invoice = $args[1];
OK

2024-11-06 12:58 UTC, TristanBouchierAgenceDnD commented on Plugin/CaptureStandardDeferredPayment.php
> +        if ($payplugPaymentId) {
OK

2024-11-06 13:13 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/Ipn.php
> +        return null;
OK

2024-11-06 13:16 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/PaymentReturn.php
> +        return false;
OK

2024-11-06 13:51 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +        $quoteIds = [];
OK

2024-11-06 13:58 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +            $deferredPaymentValidationDate = new DateTime();
OK

2024-11-06 13:59 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +            if ($difference->days >= 6) {
I used a constant, because the limitation comes from Payplug deals with the banks and wouldn't change any soon, and isn't supposed to be modified.

2024-11-06 14:07 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/PaymentReturn.php
> +            //If this is the deferred standard paiement then return the user on the success checkout
OK, harmonized with a space

2024-11-06 14:11 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +        private Message $laminas,
OK

2024-11-06 14:26 UTC, TristanBouchierAgenceDnD commented on Observer/SetDeferredProcessingOrderStatus.php
> +<?php
Not yet, we are debating about having some at some point but it is not urgent

2024-11-06 14:28 UTC, TristanBouchierAgenceDnD commented on Setup/Patch/Data/CreateFailedCaptureOrderStatus.php
> +        $this->moduleDataSetup->endSetup();
OK

2024-11-06 14:42 UTC, TristanBouchierAgenceDnD commented on Helper/Data.php
> +        }
OK

2024-11-06 14:44 UTC, TristanBouchierAgenceDnD commented on Helper/Transaction/AbstractBuilder.php
> +        }
OK

2024-11-06 15:02 UTC, TristanBouchierAgenceDnD commented on Setup/Patch/Data/CreateFailedCaptureOrderStatus.php
> +        $this->moduleDataSetup->startSetup();
OK

2024-11-13 09:29 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/Ipn.php
> +use Magento\Sales\Model\Order\Payment\Repository;
OK

2024-11-13 09:29 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/Ipn.php
> +use Magento\Sales\Model\OrderRepository;
OK

2024-11-13 09:39 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +use Magento\Sales\Model\Order\Payment\Repository;
OK

2024-11-13 09:39 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +use Magento\Sales\Model\OrderRepository;
OK

2024-11-13 09:40 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +use Magento\Sales\Model\Service\InvoiceService;
OK

2024-11-13 10:04 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +            )->setIsCustomerNotified(true)->save();
OK tested

2024-11-13 10:04 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +            )->setIsCustomerNotified(false)->save();
OK

2024-11-13 12:08 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +        $this->laminas->setSubject($subject);
OK added the transportBuilder

2024-11-13 12:15 UTC, TristanBouchierAgenceDnD commented on Helper/Config.php
> +    public function setPayplugApiKey(mixed $storeId, bool $isSandbox): void
OK

2024-11-13 12:16 UTC, TristanBouchierAgenceDnD commented on Helper/Config.php
> +    public function getApiKey($isSandbox, mixed $storeId = null): ?string
OK

2024-11-13 12:17 UTC, TristanBouchierAgenceDnD commented on Helper/Config.php
>          if ($isSandbox) {
OK

2024-11-13 12:22 UTC, TristanBouchierAgenceDnD commented on Helper/Config.php
> +    public function isOneClick(mixed $storeId = null): mixed
OK

2024-11-13 12:23 UTC, TristanBouchierAgenceDnD commented on Helper/Config.php
>          return $this->getConfigValue('payment_page') == self::PAYMENT_PAGE_INTEGRATED;
OK

2024-11-13 12:25 UTC, TristanBouchierAgenceDnD commented on Helper/Config.php
> +    public function setConfigValue(string $field, string $value, string $scope = ScopeInterface::SCOPE_STORE, mixed $scopeId = null, ?string $path = null): void
OK

2024-11-13 13:13 UTC, TristanBouchierAgenceDnD commented on Helper/Transaction/ApplePayBuilder.php
>  use Magento\Quote\Model\Quote;
OK

2024-11-13 13:13 UTC, TristanBouchierAgenceDnD commented on Helper/Transaction/BancontactBuilder.php
>  use Magento\Quote\Model\Quote;
OK

2024-11-13 13:13 UTC, TristanBouchierAgenceDnD commented on Helper/Transaction/IdealBuilder.php
>  use Magento\Quote\Model\Quote;
OK

2024-11-13 13:13 UTC, TristanBouchierAgenceDnD commented on Helper/Transaction/InstallmentPlanBuilder.php
>  use Magento\Quote\Model\Quote;
OK

2024-11-13 13:14 UTC, TristanBouchierAgenceDnD commented on Helper/Transaction/MybankBuilder.php
>  use Magento\Quote\Model\Quote;
OK

2024-11-13 13:15 UTC, TristanBouchierAgenceDnD commented on Helper/Transaction/OndemandBuilder.php
>  use Magento\Quote\Model\Quote;
OK

2024-11-13 13:20 UTC, TristanBouchierAgenceDnD commented on Helper/Transaction/OneyBuilder.php
>  use Magento\Quote\Model\Quote;
OK

2024-11-13 13:28 UTC, TristanBouchierAgenceDnD commented on Helper/Transaction/OneyBuilder.php
>  use Magento\Sales\Model\Order\Item;
OK

2024-11-13 13:28 UTC, TristanBouchierAgenceDnD commented on Helper/Transaction/SatispayBuilder.php
>  use Magento\Quote\Model\Quote;
OK

2024-11-13 13:29 UTC, TristanBouchierAgenceDnD commented on Helper/Transaction/StandardBuilder.php
>  use Magento\Quote\Model\Quote;
OK

2024-11-13 13:49 UTC, TristanBouchierAgenceDnD commented on Observer/SetDeferredAfterInvoiceOrderStatus.php
> +use Magento\Sales\Model\Order;
OK

2024-11-13 13:53 UTC, TristanBouchierAgenceDnD commented on Observer/SetDeferredAfterInvoiceOrderStatus.php
> +use Magento\Sales\Model\OrderRepository;
OK

2024-11-13 13:55 UTC, TristanBouchierAgenceDnD commented on Observer/SetDeferredProcessingOrderStatus.php
> +use Magento\Sales\Model\Order;
OK

2024-11-13 14:01 UTC, TristanBouchierAgenceDnD commented on Plugin/CaptureStandardDeferredPayment.php
> +use Magento\Quote\Model\QuoteRepository;
OK

2024-11-13 14:02 UTC, TristanBouchierAgenceDnD commented on Plugin/CaptureStandardDeferredPayment.php
> +use Magento\Sales\Model\Order;
OK

2024-11-13 14:02 UTC, TristanBouchierAgenceDnD commented on Plugin/CaptureStandardDeferredPayment.php
> +use Magento\Sales\Model\OrderRepository;
OK

2024-11-13 14:16 UTC, TristanBouchierAgenceDnD commented on Plugin/CreatePayplugTransactionOnAuthorizeOnly.php
> +use Magento\Quote\Model\QuoteRepository;
OK

2024-11-13 14:23 UTC, TristanBouchierAgenceDnD commented on Setup/Patch/Data/CreateFailedCaptureOrderStatus.php
> +use Magento\Sales\Model\Order;
OK

2024-11-13 15:51 UTC, Dnd-Mafer approved these changes

2024-11-15 17:52 UTC, AntoineKociubaAgenceDnD requested changes

2024-11-15 17:52 UTC, AntoineKociubaAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +            ->addFieldToFilter('additional_information', ['like' => '%is_authorized%'])
I'm wondering in terms of performance/slow query on a huge existing `sales_order_payment` table with those 2 filters against a `TEXT` column (so not indexed).

Is there any alternative here to avoid completely such filter eventuality ?

2024-11-15 17:52 UTC, AntoineKociubaAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +        foreach($quotePayments as $quotePayment) {
code format KO here (to be done on all modified files)

2024-11-15 17:52 UTC, AntoineKociubaAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +        if (!$orderId) {
is this scenario really possible, as order comes from order collection filtered by IDs ?

2024-11-15 17:52 UTC, AntoineKociubaAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +        $this->transportBuilder->setTemplateIdentifier('auto_capture_email_template')->setTemplateOptions(
avoid chaining in one line, not ideal for the lisibility.

2024-11-15 17:52 UTC, AntoineKociubaAgenceDnD commented on Observer/SetDeferredAfterInvoiceOrderStatus.php
> +use Magento\Sales\Model\Order;
to be removed if it became unused then (check all files -> Optimize imports)

2024-11-15 17:52 UTC, AntoineKociubaAgenceDnD commented on Plugin/CaptureStandardDeferredPayment.php
> +use Magento\Sales\Model\Order;
Still in use then ?

2024-11-15 17:52 UTC, AntoineKociubaAgenceDnD commented on Setup/Patch/Data/CreateFailedCaptureOrderStatus.php
> +use Magento\Sales\Model\Order;
still in use then ?

2024-11-15 17:52 UTC, AntoineKociubaAgenceDnD commented on Setup/Patch/Data/CreateFailedCaptureOrderStatus.php
> +use Magento\Sales\Api\Data\OrderInterface as MagentoOrderInterface;
Seems unused at the end no ?

2024-11-22 11:37 UTC, TristanBouchierAgenceDnD commented on Setup/Patch/Data/CreateFailedCaptureOrderStatus.php
> +use Magento\Sales\Api\Data\OrderInterface as MagentoOrderInterface;
Yes, I removed it because it was useless

2024-11-22 11:38 UTC, TristanBouchierAgenceDnD commented on Setup/Patch/Data/CreateFailedCaptureOrderStatus.php
> +use Magento\Sales\Api\Data\OrderInterface as MagentoOrderInterface;
https://github.com/payplug/payplug-magento2/pull/238#discussion_r1844249081
For this message right up there, about the Order being used it is because the order was only used to access a constant line 77

Order::STATE_PROCESSING
I can't use the OrderInterface for that

<img width="276" alt="Capture d’écran 2024-11-22 à 12 35 03" src="https://github.com/user-attachments/assets/79191e9d-d3e4-4679-a388-d17a6077bdfa">

2024-11-22 11:44 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +        $this->transportBuilder->setTemplateIdentifier('auto_capture_email_template')->setTemplateOptions(
OK changed

2024-11-22 11:46 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +        if (!$orderId) {
True, removed

2024-11-22 11:46 UTC, TristanBouchierAgenceDnD commented on Setup/Patch/Data/CreateFailedCaptureOrderStatus.php
> +use Magento\Sales\Api\Data\OrderInterface as MagentoOrderInterface;
<img width="785" alt="Capture d’écran 2024-11-22 à 12 32 36" src="https://github.com/user-attachments/assets/3110dfa7-cdf5-4ffc-a47d-bf718f3895f1">

2024-11-22 11:47 UTC, TristanBouchierAgenceDnD commented on Setup/Patch/Data/CreateFailedCaptureOrderStatus.php
> +use Magento\Sales\Api\Data\OrderInterface as MagentoOrderInterface;
<img width="793" alt="Capture d’écran 2024-11-22 à 12 47 42" src="https://github.com/user-attachments/assets/c0a27f6d-6daa-4d27-8572-31b7e6526d51">

2024-11-22 12:28 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +        foreach($quotePayments as $quotePayment) {
OK

2024-11-22 12:30 UTC, TristanBouchierAgenceDnD commented on Plugin/CaptureStandardDeferredPayment.php
> +use Magento\Sales\Model\Order;
Yes to access a constant that can't be referenced via the interface line 87
<img width="794" alt="Capture d’écran 2024-11-22 à 13 29 39" src="https://github.com/user-attachments/assets/e89698f9-9855-453a-8114-4f1a8ad728f0">
<img width="606" alt="Capture d’écran 2024-11-22 à 13 29 28" src="https://github.com/user-attachments/assets/e0b5850d-9a89-4a1d-9f25-18164bb30fb0">

2024-11-22 12:32 UTC, TristanBouchierAgenceDnD commented on Observer/SetDeferredAfterInvoiceOrderStatus.php
> +use Magento\Sales\Model\Order;
It didn't become unused as it is being used to get a constant line 44
<img width="616" alt="Capture d’écran 2024-11-22 à 13 31 31" src="https://github.com/user-attachments/assets/b9830005-d49b-46e0-a666-a960e10a5102">
We cannot access it via the interface
<img width="828" alt="Capture d’écran 2024-11-22 à 13 32 22" src="https://github.com/user-attachments/assets/be761dbc-49b6-48f2-86c3-9b8aeb4ea770">

2024-11-22 12:38 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +            ->addFilter('additional_information', '%fail_to_capture%', 'nlike')
We could create those two fields on the database, but i'm unsure that would be the best idea for the customer of the module. Moreover, there is a filter first on the standard payment methode that have no invoice created yet, before starting to filter on the additionnal information text field, which mean we filter against text column only on the unpaid orders, which shouldn't be numerous.

2024-11-22 12:42 UTC, TristanBouchierAgenceDnD commented on Cron/AutoCaptureDeferredPayments.php
> +        )->setTemplateVars($variables)->addTo($toMail)->setReplyTo($toMail)->getTransport()->sendMessage();
OK

2024-11-22 12:45 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/Standard.php
> +        protected Config $config
Yes removed !

2024-11-22 12:54 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/Ipn.php
> +        if ($order->getIncrementId() || !$payment->metadata['ID Quote']) {
OK

2024-11-22 13:08 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/Ipn.php
> +use Magento\Sales\Model\Order\Payment\Repository;
OK

2024-11-22 13:08 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/Ipn.php
> +use Magento\Sales\Model\OrderRepository;
OK

2024-11-22 13:10 UTC, TristanBouchierAgenceDnD commented on Setup/Patch/Data/CreateFailedCaptureOrderStatus.php
> +use Magento\Sales\Model\Order;
Yes l'order est seulement utilisée pour acceder à une constante, qui ne peut pas être récupérée via l'OrderInterface 
<img width="739" alt="Capture d’écran 2024-11-22 à 14 09 22" src="https://github.com/user-attachments/assets/81a8f2ae-f51d-472b-9fa1-c0eaeb5b74d4">
<img width="638" alt="Capture d’écran 2024-11-22 à 14 09 02" src="https://github.com/user-attachments/assets/0ce2b50f-3927-4454-9437-2abf1af4c76e">

2024-11-22 13:36 UTC, TristanBouchierAgenceDnD commented on Api/Data/OrderInterface.php
> +interface OrderInterface extends BaseOrderInterface
Changed

2024-11-22 14:02 UTC, TristanBouchierAgenceDnD commented on Controller/Payment/Ipn.php
> +    private function isStandardDeferredPayment(OrderInterface $order, Payment $payment): ?Quote
OK

2024-11-25 09:56 UTC, AntoineKociubaAgenceDnD approved these changes

2025-01-13 10:27 UTC, merged